config/routes.rb
Rails.application.routes.draw do
  #resources :insumos
 #  resources :cidades do
	# resources :distribuidoras
 #  end

 	# resources :insumos do
  #     resources :cidades do
  #       resources :distribuidoras
  #     end
  # 	end

	resources :cidades do
		resources :distribuidoras do
			resources :insumos
		end
	end
 
	root 'pages#local'
 	
 	devise_for :users
	authenticated :user do
    	root 'admin#index', as: :authenticated_root
  	end
	# get '/cidades' => 'cidades#index'
	get '/admin' => 'admin#index'
	delete '/admin' => 'admin#index'
	get 'pages/select' => 'pages#select'
	delete 'pages/select' => 'pages#select'
	get 'pages/select2' => 'pages#select2'
	delete 'pages/select2' => 'pages#select2'
	get 'pages/select3' => 'pages#select3'
	delete 'pages/select3' => 'pages#select3'
	#patch		'/cidades/:id' => 'admin#index'
	#post   'sign_in'   => 'sessions#create'
	#delete 'sign_out'  => 'sessions#destroy'
	#resources :pages do
		#resources :admin
	#end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/_header.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>


<nav class="navbar navbar-light" role="navigation" style="background: #b4e391; /* Old browsers */
background: -moz-linear-gradient(top, #b4e391 0%, #61c419 28%, #b4e391 100%); /* FF3.6-15 */
background: -webkit-linear-gradient(top, #b4e391 0%,#61c419 28%,#b4e391 100%); /* Chrome10-25,Safari5.1-6 */
background: linear-gradient(to bottom, #b4e391 0%,#61c419 28%,#b4e391 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#b4e391', endColorstr='#b4e391',GradientType=0 ); /* IE6-9 */" >
  
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to ' Home', root_path, class:'navbar-brand glyphicon glyphicon-home' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cidades <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Cadastrar', new_cidade_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Atualizar/Remover', cidades_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Distribuidoras <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Cadastrar', new_distribuidora_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Atualizar/Remover', distribuidoras_path %></li>
          </ul>
        </li>
      </ul>
     <!--  <form class="navbar-form navbar-left" role="search">
        <div class="input-group">
          <%= text_field_tag :keywords,
          params[:keywords],
          autocomplete: "off",
          placeholder: "Cidade, distribuidora ...",
          class: 'form-control typeahead',
          autofocus: true,
          id: 'lists_search' %>
        </div>
          <button type="submit" class="btn btn-primary">
            <i class="glyphicon glyphicon-search"></i>
          </button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <div class="navbar-brand"><small>Logado como <strong><%= current_user.username %></strong></small></div>
            <%= link_to  ' Perfil',  edit_user_registration_path, class:'navbar-brand glyphicon glyphicon-user ' %>
            <%= link_to " Sair ", destroy_user_session_path, method: :delete, class:'navbar-brand glyphicon glyphicon-off' %>
          <% else %>
            <!--<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |-->
            <%= link_to " Acessar", new_user_session_path, class:'navbar-brand glyphicon glyphicon-log-in'  %>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

  </div>
</div>

app/views/admin/index.html.erb

<div class="container">
  <div class="row">
    <div class="middle">
      <h2>Lista de Insumos e Serviços Cadastrados</h2>
    </div>
        <div class="col-lg-12">
            <input type="search" class="form-control" id="input-search" placeholder="Pesquise Insumos ou Serviços..." >
        </div>
        <div class="searchable-container">
          <% @cidades.each do |cidade| %>
            <% cidade.distribuidoras.each do |dist| %>
              <% dist.insumos.each do |insu| %>
                <div class="items col-xs-12 col-sm-6 col-md-6 col-lg-6 clearfix">
                  <br/><div class="info-block block-info clearfix">
                    <div class="square-box pull-left">
                       <%= image_tag insu.foto.url if insu.foto? %>
                    </div>
                      <h4><%= insu.tipo %></h4>
                      <h5>Cidade: <%= cidade.nome %></h5>
                      <h5>Distribuidora: <%= dist.nome %></h5>
                      <h5>Preço: R<%= number_to_currency(insu.preco) %></h5>
                      <h5>Descrição: <%= insu.descricao %></h5>
                      <%= link_to edit_cidade_distribuidora_insumo_path(cidade, dist, insu), class:'btn btn-link' do %>
                        <i class="glyphicon glyphicon-edit"> Editar</i>
                      <% end %>
                      <%= link_to cidade_distribuidora_insumo_path(cidade, dist, insu), method: :delete, data:{confirm: "Deseja remover esse Registro?"}, class:'btn btn-link' do %>
                        <i class="glyphicon glyphicon-remove-sign"> Remover</i>
                      <% end %>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
  </div>
</div>  