config/routes.rb
Rails.application.routes.draw do
  #resources :insumos
 #  resources :cidades do
	# resources :distribuidoras
 #  end

 	# resources :insumos do
  #     resources :cidades do
  #       resources :distribuidoras
  #     end
  # 	end

	resources :cidades do
		resources :distribuidoras do
			resources :insumos
		end
	end
 
	root 'pages#local'
 	
 	devise_for :users
	authenticated :user do
    	root 'admin#index', as: :authenticated_root
  	end
	# get '/cidades' => 'cidades#index'
	get '/admin' => 'admin#index'
	delete '/admin' => 'admin#index'
	get 'pages/select' => 'pages#select'
	delete 'pages/select' => 'pages#select'
	get 'pages/select2' => 'pages#select2'
	delete 'pages/select2' => 'pages#select2'
	get 'pages/select3' => 'pages#select3'
	delete 'pages/select3' => 'pages#select3'
	#patch		'/cidades/:id' => 'admin#index'
	#post   'sign_in'   => 'sessions#create'
	#delete 'sign_out'  => 'sessions#destroy'
	#resources :pages do
		#resources :admin
	#end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/insumo.rb
class Insumo < ApplicationRecord
	#has_many :distribuidoras, dependent: :destroy
	#has_many :cidades
	belongs_to :distribuidoras, optional: true
	mount_uploader :foto, ImageUploader
  	#belongs_to :cidade, optional: true
  	#accepts_nested_attributes_for :distribuidoras, allow_destroy: true
  	#accepts_nested_attributes_for :cidades, allow_destroy: true
	validates :tipo, :preco, :latitude, :longitude, :descricao, presence:true, allow_blank:true
	validates_length_of :descricao, maximum: 200
	validates_format_of :icone, allow_blank:true, with: /\w+\.(gif|jpeg|png)\z/i, message:"Utilizar somente arquivos GIF, JPEG ou PNG"
	#validates_format_of :foto, allow_blank:true, with: /\w+\.(gif|jpeg|png)\z/i, message:"Utilizar somente arquivos GIF, JPEG ou PNG"

	#validates_associated :distribuidoras
	#validates_associated :cidades
	validates_processing_of :foto
	validate :image_size_validation
 
private
  
  def image_size_validation
    errors[:foto] << "should be less than 500KB" if foto.size > 0.5.megabytes
  end

end

app/controllers/insumos_controller.rb
class InsumosController < ApplicationController
  #before_action :set_insumo, only: [:show, :edit, :update, :destroy]
  before_action :set_distribuidora
  before_action :set_cidade
  # GET /insumos
  # GET /insumos.json
  def index
    #@distribuidoras = @cidade.distribuidoras
    @insumos = @distribuidora.insumos
  end

  # GET /insumos/1
  # GET /insumos/1.json
  def show
    @insumo = Insumo.find(params[:id])
  end

  # GET /insumos/new
  def new

    @insumo = @distribuidora.insumos.new
    #@insumo = @cidades.distribuidoras.insumos.new
    #@insumo.cidades.build
    #@insumo.distribuidoras.build
  end

  # GET /insumos/1/edit
  def edit
    @insumo = Insumo.find(params[:id])
  end

  # POST /insumos
  # POST /insumos.json
  def create 
    #@distribuidora = @cidade.distribuidoras
    @insumo = @distribuidora.insumos.new(insumo_params)
    #@insumo = Insumo.new(insumo_params)

    respond_to do |format|
      if @insumo.save
        format.html { redirect_to admin_path, notice: 'Insumo was successfully created.' }
        format.json { render :show, status: :created, location: @insumo }
      else
        format.html { render :new }
        format.json { render json: @insumo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insumos/1
  # PATCH/PUT /insumos/1.json
   def update
    respond_to do |format|
      @insumo = Insumo.find(params[:id])
      if @insumo.update(insumo_params)
        format.html { redirect_to admin_path, notice: 'Insumo was successfully updated.' }
        format.json { render :show, status: :ok, location: @insumo }
      else
        format.html { render :edit }
        format.json { render json: @insumo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insumos/1
  # DELETE /insumos/1.json
  def destroy
    @insumo = Insumo.find(params[:id])
    @insumo.destroy
    respond_to do |format|
      format.html { redirect_to insumos_url, notice: 'Insumo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_distribuidora
      @distribuidora = Distribuidora.find(params[:distribuidora_id])   
    end

    def set_cidade
      @cidade = Cidade.find(params[:cidade_id])   
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insumo_params
      params.require(:insumo).permit(:tipo, :preco, :descricao, :latitude, :longitude, :icone, :foto)
      #params.require(:insumo).permit(:tipo, :preco, :descricao, :latitude, :longitude, :icone, :foto, distribuidoras_attributes:[:id, :insumo_id, :nome, :latitude, :longitude, :descricao, :icone, :foto, :_destroy], cidades_attributes:[:id, :insumo_id, :nome,:uf, :_destroy])
    end
end

app/helpers/insumos_helper.rb
module InsumosHelper
end

app/views/insumos/_form.html.erb
<%= form_for ([@cidade, @distribuidora, @insumo]), html: { multipart: true} do |f| %>

<%= render 'layouts/errors' , object: @insumo %>

<p class="form-group">
  <%= f.label :Nome %></br>
  <%= f.text_field :tipo, class:"form-control" %>
</p>

<p class="form-group">
  <%= f.label :Preco %></br>
  <%= f.number_field :preco, class:"form-control" %>
</p>

<p class="form-group">
  <%= f.label :Latitude %></br>
  <%= f.number_field :latitude, class:"form-control" %>
</p>
<p class="form-group">
  <%= f.label :Longitude %></br>
  <%= f.number_field :longitude, class:"form-control" %>
</p>
<p class="form-group">
  <%= f.label :Descrição %></br>
  <%= f.text_area :descricao, class:"form-control" %>
</p>
<p class="form-group">
  <%= f.label :Foto %></br>
  <%= f.file_field :foto %>
</p>

<p>
      <div class="actions">
                  <%= f.submit class:'btn btn-primary' %>
                  <%= link_to 'Cancelar', admin_path, class: 'btn btn-default' %>
      </div>  
</p>

<% end %>

app/views/insumos/edit.html.erb
<div class='container'>
<div class="panel panel-default">
  <div class="panel-heading">
  	<h2>Editar Insumo/Serviço</h2>
  </div>
  <div class="panel-body">
	<%= render 'form'%>
  </div>
</div>
</div>

app/views/insumos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Insumos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Preco</th>
      <th>Descricao</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Icone</th>
      <th>Foto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insumos.each do |insumo| %>
      <tr>
        <td><%= insumo.tipo %></td>
        <td><%= insumo.preco %></td>
        <td><%= insumo.descricao %></td>
        <td><%= insumo.latitude %></td>
        <td><%= insumo.longitude %></td>
        <td><%= insumo.icone %></td>
        <td><%= insumo.foto %></td>
        <td><%= link_to 'Show', insumo %></td>
        <td><%= link_to 'Edit', edit_insumo_path(insumo) %></td>
        <td><%= link_to 'Destroy', insumo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/insumos/new.html.erb
<div class='container'>
<div class="panel panel-default">
  <div class="panel-heading">
  	<h2>Cadastrando Insumos ou Serviços</h2>
  </div>
  <div class="panel-body">
	<%= render 'form'%>
  </div>
</div>
</div>

app/views/insumos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @insumo.tipo %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @insumo.preco %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @insumo.descricao %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @insumo.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @insumo.longitude %>
</p>

<p>
  <strong>Icone:</strong>
  <%= @insumo.icone %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @insumo.foto %>
</p>