config/routes.rb
Rails.application.routes.draw do
  #resources :insumos
 #  resources :cidades do
	# resources :distribuidoras
 #  end

 	# resources :insumos do
  #     resources :cidades do
  #       resources :distribuidoras
  #     end
  # 	end

	resources :cidades do
		resources :distribuidoras do
			resources :insumos
		end
	end
 
	root 'pages#local'
 	
 	devise_for :users
	authenticated :user do
    	root 'admin#index', as: :authenticated_root
  	end
	# get '/cidades' => 'cidades#index'
	get '/admin' => 'admin#index'
	delete '/admin' => 'admin#index'
	get 'pages/select' => 'pages#select'
	delete 'pages/select' => 'pages#select'
	get 'pages/select2' => 'pages#select2'
	delete 'pages/select2' => 'pages#select2'
	get 'pages/select3' => 'pages#select3'
	delete 'pages/select3' => 'pages#select3'
	#patch		'/cidades/:id' => 'admin#index'
	#post   'sign_in'   => 'sessions#create'
	#delete 'sign_out'  => 'sessions#destroy'
	#resources :pages do
		#resources :admin
	#end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/distribuidora.rb
class Distribuidora < ApplicationRecord
	validates :nome, :latitude, :longitude, :descricao, presence:true, allow_blank: true
	validates_length_of :descricao, maximum: 200
	validates_format_of :icone, allow_blank:true, with: /\w+\.(gif|jpeg|png)\z/i, message:"Utilizar somente arquivos GIF, JPEG ou PNG"
	validates_format_of :foto, allow_blank:true, with: /\w+\.(gif|jpeg|png)\z/i, message:"Utilizar somente arquivos GIF, JPEG ou PNG"
	#belongs_to :insumo, optional: true
  	belongs_to :cidade, optional: true
  	has_many :insumos, dependent: :destroy
end

app/controllers/distribuidoras_controller.rb
class DistribuidorasController < ApplicationController
	before_action :authenticate_user!
	before_action :set_cidade

	def index
		 @distribuidoras = @cidade.distribuidoras
	end

	def edit
		@distribuidora = Distribuidora.find(params[:id])
	end

	def update
		@distribuidora = Distribuidora.find(params[:id])
		respond_to do |format|
      if @distribuidora.update(distribuidora_params)
        format.html { redirect_to cidade_distribuidoras_path(@cidade), notice: 'distribuidora was successfully updated.' }
        format.json { render :show, status: :ok, location: @distribuidora }
      else
        format.html { render :edit }
        format.json { render json: @distribuidora.errors, status: :unprocessable_entity }
      end
    end
	end

	def show
		@distribuidora = Distribuidora.find(params[:id])
	end

	def new
		@distribuidora = @cidade.distribuidoras.new
	end

	def create
		@distribuidora = @cidade.distribuidoras.new(distribuidora_params)
    	respond_to do |format|
      		if @distribuidora.save
        		format.html { redirect_to admin_path, notice: 'Distribuidora was successfully created.' }
        		format.json { render :show, status: :created, location: @distribuidora }
      		else
        		format.html { render :new }
        		format.json { render json: @distribuidora.errors, status: :unprocessable_entity }
      		end
    	end
	end

	def destroy
		@distribuidora = Distribuidora.find(params[:id])
		@distribuidora.destroy
		redirect_to distribuidoras_url, alert:"Distribuidora apagada com sucesso!"
	end

	private

		def distribuidora_params
			params.require(:distribuidora).permit(:nome, :latitude, :longitude, :descricao, :icone, :foto)
		end

		def set_cidade
			@cidade = Cidade.find(params[:cidade_id])		
		end

end

app/helpers/distribuidoras_helper.rb
module DistribuidorasHelper
end

app/views/distribuidoras/_form.html.erb
<%= form_for ([@cidade, @distribuidora]) do |f| %>

<%= render 'layouts/errors' , object: @distribuidora %>
	
<p class="form-group">
	<%= f.label :Nome %></br>
	<%= f.text_field :nome, class:"form-control" %>
</p>
<p class="form-group">
	<%= f.label :Latitude %></br>
	<%= f.number_field :latitude, class:"form-control" %>
</p>
<p class="form-group">
	<%= f.label :Longitude %></br>
	<%= f.number_field :longitude, class:"form-control" %>
</p>
<p class="form-group">
	<%= f.label :Descrição %></br>
	<%= f.text_area :descricao, class:"form-control" %>
</p>
<p>
	<%= f.submit class:'btn btn-primary' %>
	<%= link_to 'Cancelar', admin_path, class: 'btn btn-default' %>
</p>

<% end %>

app/views/distribuidoras/edit.html.erb
<div class='container'>
<div class="panel panel-default">
  <div class="panel-heading">
  	<h2>Editar Distribuidora</h2>
  </div>
  <div class="panel-body">
	<%= render 'form'%>
  </div>
</div>
</div>

app/views/distribuidoras/index.html.erb
<center>
<div class="container-fluid">
	<% if @cidade.distribuidoras.size > 0 %>
		<div class="col-md-10">
	 		<h2>Distribuidora Cadastradas</h2>
		</div>
		<div class="col-md-10">
			<% @cidade.distribuidoras.each do |dist| %>	
				<div class="span6">
					<p><h3 class="text-left"><%= dist.nome %></h3></p>
						<td class="text-center">
							<%= link_to edit_cidade_distribuidora_path(@cidade, dist), class:'btn btn-link' do %>
	                    		<i class="glyphicon glyphicon-edit"> Editar</i>
	                  		<% end %>
	                  		<%= link_to cidade_distribuidora_path(@cidade, dist), method: :delete, data:{confirm: "Deseja remover esse Registro?"}, class:'btn btn-link' do %>
	                    		<i class="glyphicon glyphicon-remove-sign"> Remover</i>
	                  		<% end %>
              			</td>
				</div>
			<% end %>
		</div>
	<% else %>
		<div class="jumbotron">
			<h3>Não há Distribuidoras cadastradas!</h3>
		</div>
	<% end %>
		<div class="col-md-8">
			<p><%= link_to admin_path, class:'btn btn-link' do %>
	 			<i class="glyphicon glyphicon-home"> Voltar</i>
				<% end %>
			</p>
		</div>
</div>
</center>

app/views/distribuidoras/new.html.erb
<div class='container'>
<div class="panel panel-default">
  <div class="panel-heading">
  	<h2>Cadastrando Novas Distribuidoras</h2>
  </div>
  <div class="panel-body">
	<%= render 'form'%>
  </div>
</div>
</div>

app/views/distribuidoras/show.html.erb
<div class="container">
<div class="jumbotron">
<article>
 	<header>
 		<p><h1>Tag</h1></p>
 	</header>
 </article>
</div>

<%= link_to new_cidade_distribuidora_path(@cidade), class:'btn btn-link' do %>
 	<i class="glyphicon glyphicon-tower"> Cadastrar Distribuidora</i>
<% end %>

<%= link_to cidades_path, class:'btn btn-link' do %>
 	<i class="glyphicon glyphicon-home"> Voltar</i>
<% end %>

<%= link_to edit_cidade_distribuidora_path(@cidade), class:'btn btn-link' do %>
	<i class="glyphicon glyphicon-edit"> Editar</i>
<% end %>

 <%= link_to cidade_distribuidora_path(@cidade), method: :delete, data:{confirm: "Deseja deletar essa Distribuidora?"}, class:'btn btn-link' do %>
 	<i class="glyphicon glyphicon-remove-sign"> Deletar</i>
 <% end %>

</div>