config/routes.rb
Rails.application.routes.draw do
  #resources :insumos
 #  resources :cidades do
	# resources :distribuidoras
 #  end

 	# resources :insumos do
  #     resources :cidades do
  #       resources :distribuidoras
  #     end
  # 	end

	resources :cidades do
		resources :distribuidoras do
			resources :insumos
		end
	end
 
	root 'pages#local'
 	
 	devise_for :users
	authenticated :user do
    	root 'admin#index', as: :authenticated_root
  	end
	# get '/cidades' => 'cidades#index'
	get '/admin' => 'admin#index'
	delete '/admin' => 'admin#index'
	get 'pages/select' => 'pages#select'
	delete 'pages/select' => 'pages#select'
	get 'pages/select2' => 'pages#select2'
	delete 'pages/select2' => 'pages#select2'
	get 'pages/select3' => 'pages#select3'
	delete 'pages/select3' => 'pages#select3'
	#patch		'/cidades/:id' => 'admin#index'
	#post   'sign_in'   => 'sessions#create'
	#delete 'sign_out'  => 'sessions#destroy'
	#resources :pages do
		#resources :admin
	#end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cidade.rb
class Cidade < ApplicationRecord
	has_many :distribuidoras, dependent: :destroy
	has_many :insumos, through: :distribuidoras, dependent: :destroy
	#belongs_to :insumo, optional: true
	validates :nome,:uf, presence:true, allow_blank: true
	validates_uniqueness_of :nome, :scope => :uf

	#accepts_nested_attributes_for :distribuidoras, allow_destroy: true
	#validates_associated :distribuidoras
	
	UF = %w(AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO)
	validates_inclusion_of :uf, in: UF

	def self.created_at
		where('created_at <= ?' , Time.now).order('created_at desc')
	end


end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController
before_action :authenticate_user!

	def index
		 @cidades = Cidade.created_at 
	end

	def show
		@cidade = Cidade.find(params[:id])
	end

	def edit
		@cidade = Cidade.find(params[:id])
	end

	def update
		@cidade = Cidade.find(params[:id])
		if @cidade.update(cidade_params)
			redirect_to cidades_path, notice:"Cidade modificada com sucesso!"
		else
			render :edit
		end

	end

	def new
		@cidade = Cidade.new
		#@cidade.distribuidoras.build
	end

	def create
		@cidade = Cidade.new(cidade_params)
    	respond_to do |format|
      		if @cidade.save
        		format.html { redirect_to admin_path, notice: 'cidade was successfully created.' }
        		format.json { render :show, status: :created, location: @cidade }
      		else
        		format.html { render :new }
        		format.json { render json: @cidade.errors, status: :unprocessable_entity }
      		end
    	end
	end

	def destroy
		@cidade = Cidade.find(params[:id])
		@cidade.destroy
		redirect_to cidades_url, alert:"Cidade apagada com sucesso!"
	end

	private

	def cidade_params
		#params.require(:cidade).permit(:nome,:uf, distribuidoras_attributes:[:id, :cidade_id, :nome, :latitude, :longitude, :descricao, :icone, :foto, :_destroy])
	params.require(:cidade).permit(:nome,:uf)
	
	end

end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/views/cidades/_form.html.erb
<%= form_for(@cidade) do |f| %>

<%= render 'layouts/errors' , object: @cidade %>
	
<p class="form-group">
	<%= f.label :Nome %></br>
	<%= f.text_field :nome, class:"form-control" %>
</p>
<p class="form-group">
	<%= f.label :UF %></br>
	<%= f.select :uf, Cidade::UF, prompt: 'Escolha o Estado', class:"form-control" %>
</p>
<p>
	<%= f.submit class:'btn btn-primary' %>
	<%= link_to 'Cancelar', admin_path, class: 'btn btn-default' %>
</p>

<% end %>

app/views/cidades/edit.html.erb
<div class='container'>
<div class="panel panel-default">
  <div class="panel-heading">
  	<h2>Editar Cidade</h2>
  </div>
  <div class="panel-body">
	<%= render 'form'%>
  </div>
</div>
</div>

app/views/cidades/index.html.erb
<center>
<div class="container-fluid">
	<% if @cidades.size > 0 %>
		<div class="col-md-10">
	 		<h2>Cidades Cadastradas</h2>
		</div>
		<div class="col-md-10">
			<% @cidades.each do |cidade| %>
				<div class="span6">
					<p><h3 class="text-left"><%= cidade.nome %></h3></p>
						<td class="text-center">
							<%= link_to edit_cidade_path(cidade), class:'btn btn-link' do %>
	                    		<i class="glyphicon glyphicon-edit"> Editar</i>
	                  		<% end %>
	                  		<%= link_to cidade_path(cidade), method: :delete, data:{confirm: "Deseja remover esse Registro?"}, class:'btn btn-link' do %>
	                    		<i class="glyphicon glyphicon-remove-sign"> Remover</i>
	                  		<% end %>
              			</td>
		 			<!-- <h3>Uf: <%= cidade.uf %></h3> -->
				</div>
			<% end %>
		</div>
	<% else %>
		<div class="jumbotron">
			<h3>Não há cidades cadastradas!</h3>
		</div>
	<% end %>
		<div class="col-md-8">
			<p><%= link_to admin_path, class:'btn btn-link' do %>
	 			<i class="glyphicon glyphicon-home"> Voltar</i>
				<% end %>
			</p>
		</div>
</div>
</center>

app/views/cidades/new.html.erb
<div class='container'>
<div class="panel panel-default">
  <div class="panel-heading">
  	<h2>Cadastrando Novas Cidades</h2>
  </div>
  <div class="panel-body">
	<%= render 'form'%>
  </div>
</div>
</div>

app/views/cidades/show.html.erb
<div class="container">
<div class="jumbotron">
<article>
 	<header>
 		<p><h1><%= @cidade.nome %></h1></p>
 		<p><h1><%= @cidade.uf %></h1></p>
 	</header>
 </article>
</div>

<%= link_to new_cidade_distribuidora_path(@cidade), class:'btn btn-link' do %>
 	<i class="glyphicon glyphicon-tower"> Cadastrar Distribuidora</i>
<% end %>

<%= link_to cidade_distribuidoras_path(@cidade), class:'btn btn-link' do %>
 	<i class="glyphicon glyphicon-tower"> Atualizar Distribuidora</i>
<% end %>

<%= link_to cidades_path, class:'btn btn-link' do %>
 	<i class="glyphicon glyphicon-home"> Voltar</i>
<% end %>

<%= link_to edit_cidade_path(@cidade), class:'btn btn-link' do %>
	<i class="glyphicon glyphicon-edit"> Editar</i>
<% end %>

 <%= link_to cidade_path(@cidade), method: :delete, data:{confirm: "Deseja deletar essa cidade?"}, class:'btn btn-link' do %>
 	<i class="glyphicon glyphicon-remove-sign"> Deletar</i>
 <% end %>

</div>